drop
    database if exists work;
create
    database work;


create table sub_category
(
    id   integer primary key GENERATED BY DEFAULT AS IDENTITY,
    type varchar(250) not null unique
);

create table category
(
    id   integer primary key GENERATED BY DEFAULT AS IDENTITY,
    type varchar(250) not null unique
);

create table users
(
    id         integer primary key GENERATED BY DEFAULT AS IDENTITY,
    login      varchar(250) not null unique,
    password   varchar(250) not null,
    email      varchar(250),
    info_id    integer,
    item_id    integer,
    product_id integer,
    role_id integer,
    foreign key (role_id) references role(id),
    foreign key (info_id) references user_info (id) on delete cascade on update cascade
);

create table role
(
    id      integer primary key GENERATED BY DEFAULT AS IDENTITY,
    type    varchar(50) not null unique
);


create table user_info
(
    id       integer primary key GENERATED BY DEFAULT AS IDENTITY,
    name     varchar(250) not null,
    lastName varchar(250),
    phone    varchar(250),
    image    varchar(250),
    birthday date         not null
);


create table product
(
    id              integer primary key GENERATED BY DEFAULT AS IDENTITY,
    user_id         integer       not null,
    name            varchar(250)  not null,
    image           varchar(250)  not null,
    description     varchar(1024) not null,
    date            date,
    price           decimal       not null,
    category_id     integer,
    sub_category_id integer,
    foreign key (user_id) references users (id),
    foreign key (category_id) references category (id),
    foreign key (sub_category_id) references sub_category (id)
);
create table item
(
    id          integer primary key GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(250) not null,
    date        date,
    description varchar(4096),
    user_id   integer,
    foreign key (user_id) references users(id)
);


create table comment
(
    id        integer primary key GENERATED BY DEFAULT AS IDENTITY,
    date      date    not null,
    author_id integer not null,
    message   varchar(4096),
    item_id   integer,
    foreign key (item_id) references item (id)
);

insert into role (type)
values ('ADMIN');
insert into role (type)
values ('MODER');

insert into users (login, password, role_id)
values ('admin', 'admin', (select id from role where type = 'ADMIN'));
insert into users (login, password, role_id)
values ('moder', 'moder', (select id from role where type = 'MODER'));

